<?php
  include_once("component/core/header.php");
  include("component/parts/navbar.php");
  include("component/parts/hero.php");
  include("component/parts/badge.php");
  include("component/parts/search_domain.php"); 
  include("component/parts/featured_card.php"); 
  include("component/parts/additional_product.php"); 
  include("component/parts/solution.php"); 
  include("component/parts/commitment.php"); 
  include("component/parts/promo_banner.php"); 
  include("component/parts/customer.php"); 
  include("component/parts/partner.php"); 
  include("component/parts/guarantee_banner.php"); 
  include("component/parts/testimonial.php"); 
  include("component/parts/covered.php"); 
  include("component/parts/payment.php"); 
  include("component/parts/qna.php"); 
  include("component/parts/contact.php"); 
  include("component/parts/office.php"); 
  include_once("component/core/footer.php"); 
?>